spring:
  datasource:
    url: jdbc:mysql://121.251.255.96:3306/yibantest
    username: yibantest
    password: yibantest
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 8087
yibanoauth:
  bulletinboard:
    APPID: "acaec190548725cf"
    APPkey: "6b7d82af041da97d586ad8b8d8204225"
